import { z } from 'zod'

// Multipart fields of a web message; the file (image or voice note) travels as "file"
export const sendMessageSchema = z.object({
  // generated by the browser: a retried request with the same id is ignored (like a Telegram webhook retry)
  messageId: z.string().trim().min(8).max(64),
  text: z.string().trim().max(1000).optional(),
  durationSeconds: z.coerce.number().int().min(0).max(3600).optional(),
})

export const messageActionSchema = z.object({
  // the "data" of a BotReply button, as the bot sends it
  data: z.string().min(1).max(64),
})
