import { z } from 'zod'

// Multipart fields of a web message; the file (image or voice note) travels as "file"
export const sendMessageSchema = z.object({
  // generated by the browser: a retried request with the same id is ignored (like a Telegram webhook retry)
  messageId: z.string().trim().min(8).max(64),
  text: z.string().trim().max(1000).optional(),
  durationSeconds: z.coerce.number().int().min(0).max(3600).optional(),
})

export const messageActionSchema = z.object({
  // the "data" of a BotReply button, as the bot sends it
  data: z.string().min(1).max(64),
})

// ==================== Responses (Swagger / kogane-app types) ====================

// The same replies the bot sends to Telegram (HTML text + inline buttons), drawn by the web chat
export const botReplySchema = z.object({
  text: z.string().describe('HTML: <b>, <i> and escaped user text'),
  buttons: z.array(z.array(z.object({ label: z.string(), data: z.string() }))).optional(),
  edit: z.boolean().optional().describe('Replace the message that had the pressed button'),
})

export const conversationResultSchema = z.object({
  replies: z.array(botReplySchema),
  notice: z.string().optional().describe('Short toast for the pressed button'),
})
