import { MASKED_VALUE, SENSITIVE_COLUMNS, UNTRACKED_COLUMNS } from '@/commons/constants/audit.constant'

// SQL of the history triggers (P29, D122). Pure: scripts/audit-triggers.ts feeds it the columns of the database and
// writes the result as a migration; the integration test feeds it the same and compares with the triggers that exist,
// so a column added without regenerating fails `make check`

export interface AuditedTable {
  table: string
  idColumn: string
  columns: string[]
}

export interface AuditTrigger {
  name: string
  sql: string // CREATE TRIGGER … END (no trailing ";")
}

const quote = (identifier: string) => `"${identifier}"`
const literal = (value: string) => `'${value.replace(/'/g, "''")}'`

const NOW = `strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'` // the format Prisma writes DateTime in
const SOURCE = `COALESCE(c."source", 'cli')`
const INSERT_INTO = `INSERT INTO "aud_changes" ("id", "entity", "entityId", "action", "changes", "source", "actorId", "batchId", "createdAt")`

// Rows of an import are not logged one by one: the importer leaves a single event (source = import)
const CONTEXT_JOIN = `LEFT JOIN "aud_context" c ON c."id" = 1`
const NOT_IMPORT = `${SOURCE} <> 'import'`

const masked = (value: string) => `CASE WHEN ${value} IS NULL THEN NULL ELSE ${literal(MASKED_VALUE)} END`
const mask = (table: string, column: string, value: string) =>
  SENSITIVE_COLUMNS[table]?.includes(column) ? masked(value) : value

function snapshotTrigger({ table, idColumn, columns }: AuditedTable, action: 'create' | 'delete'): AuditTrigger {
  const row = action === 'create' ? 'NEW' : 'OLD'
  const name = `aud_${action === 'create' ? 'ins' : 'del'}_${table}`
  const fields = columns
    .map((column) => `${literal(column)}, ${mask(table, column, `${row}.${quote(column)}`)}`)
    .join(', ')
  return {
    name,
    sql: [
      `CREATE TRIGGER ${quote(name)} AFTER ${action === 'create' ? 'INSERT' : 'DELETE'} ON ${quote(table)}`,
      'BEGIN',
      `  ${INSERT_INTO}`,
      `  SELECT lower(hex(randomblob(12))), ${literal(table)}, ${row}.${quote(idColumn)}, ${literal(action)}, json_object(${fields}), ${SOURCE}, c."actorId", c."batchId", ${NOW}`,
      `  FROM (SELECT 1) ${CONTEXT_JOIN}`,
      `  WHERE ${NOT_IMPORT};`,
      'END',
    ].join('\n'),
  }
}

function updateTrigger({ table, idColumn, columns }: AuditedTable): AuditTrigger {
  const name = `aud_upd_${table}`
  const tracked = columns.filter((column) => !UNTRACKED_COLUMNS.includes(column))
  const pairs = tracked
    .map((column, index) => {
      const select = `${literal(column)}${index === 0 ? ' AS "k"' : ''}, OLD.${quote(column)}${index === 0 ? ' AS "o"' : ''}, NEW.${quote(column)}${index === 0 ? ' AS "n"' : ''}`
      return `${index === 0 ? 'SELECT' : 'UNION ALL SELECT'} ${select}`
    })
    .join('\n      ')
  // Only what changed, [before, after]; the sensitive ones as "changed" (masked)
  const sensitive = tracked.filter((column) => SENSITIVE_COLUMNS[table]?.includes(column))
  const before = sensitive.length
    ? `CASE WHEN "k" IN (${sensitive.map(literal).join(', ')}) THEN ${masked('"o"')} ELSE "o" END`
    : '"o"'
  const after = sensitive.length
    ? `CASE WHEN "k" IN (${sensitive.map(literal).join(', ')}) THEN ${masked('"n"')} ELSE "n" END`
    : '"n"'
  return {
    name,
    sql: [
      `CREATE TRIGGER ${quote(name)} AFTER UPDATE ON ${quote(table)}`,
      'BEGIN',
      `  ${INSERT_INTO}`,
      `  SELECT lower(hex(randomblob(12))), ${literal(table)}, NEW.${quote(idColumn)}, 'update', diff."changes", ${SOURCE}, c."actorId", c."batchId", ${NOW}`,
      `  FROM (SELECT json_group_object("k", json_array(${before}, ${after})) AS "changes", COUNT(*) AS "total" FROM (`,
      `      ${pairs}`,
      `    ) WHERE "o" IS NOT "n") diff`,
      `  ${CONTEXT_JOIN}`,
      `  WHERE diff."total" > 0 AND ${NOT_IMPORT};`,
      'END',
    ].join('\n'),
  }
}

export function buildAuditTriggers(tables: AuditedTable[]): AuditTrigger[] {
  return tables.flatMap((table) => [
    snapshotTrigger(table, 'create'),
    updateTrigger(table),
    snapshotTrigger(table, 'delete'),
  ])
}

// The migration: every trigger dropped and created again, so a new column only needs the script to run again
export function auditTriggersMigration(triggers: AuditTrigger[]): string {
  return [
    '-- History triggers (P29, D122). Generated by `make audit-triggers`: do not edit by hand',
    ...triggers.map((trigger) => `DROP TRIGGER IF EXISTS ${quote(trigger.name)};`),
    '',
    ...triggers.map((trigger) => `${trigger.sql};\n`),
  ].join('\n')
}

// sqlite_master keeps the text as written; only the trailing ";" and the spacing may differ
export const normalizeTriggerSql = (sql: string) => sql.replace(/;\s*$/, '').replace(/\s+/g, ' ').trim()
