import { Body, Controller, HttpCode, HttpStatus, Post, UploadedFile, UseInterceptors } from '@nestjs/common'
import { FileInterceptor } from '@nestjs/platform-express'
import { ApiBody, ApiConsumes, ApiOperation } from '@nestjs/swagger'

import { MAX_IMAGE_BYTES } from '@/commons/constants/conversation.constant'
import { ApiRest } from '@/commons/decorators/api-rest.decorator'
import { ResponseMessage } from '@/commons/decorators/response-message.decorator'

import { MessageActionDto, SendMessageDto } from './dto/request/messages.dto'
import { MessagesService, UploadedMessageFile } from './messages.service'

@ApiRest('messages')
@Controller('messages')
export class MessagesController {
  constructor(private readonly messagesService: MessagesService) {}

  @Post()
  @HttpCode(HttpStatus.OK)
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_IMAGE_BYTES } }))
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      required: ['messageId'],
      properties: {
        messageId: { type: 'string', description: 'Generated by the browser; a retry with the same id is ignored' },
        text: { type: 'string', description: 'Message, command ("/resumen") or caption of the image' },
        durationSeconds: { type: 'integer', description: 'Voice notes only' },
        file: { type: 'string', format: 'binary', description: 'Image or voice note (≤ 10 MB)' },
      },
    },
  })
  @ApiOperation({ summary: 'Mensajes: send text, an image or a voice note to Kogane; returns the bot replies' })
  @ResponseMessage('MESSAGE_HANDLED', 'Message handled')
  send(@Body() body: SendMessageDto, @UploadedFile() file?: UploadedMessageFile) {
    return this.messagesService.send(body, file)
  }

  @Post('actions')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Press a button of a bot reply (its "data")' })
  @ResponseMessage('MESSAGE_ACTION_HANDLED', 'Message action handled')
  action(@Body() body: MessageActionDto) {
    return this.messagesService.action(body)
  }
}
